# -*- coding: utf-8 -*-
"""Л3_Имхасина.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15BISb1B2Bs1cUnfawnLFWZqa-kCaUO32

Цветное->потуновое
"""
from PIL import Image, ImageDraw

orig = Image.open("1.jpg")
orig = orig.convert('RGB')
draw = ImageDraw.Draw(orig)
w, h = orig.size	
new_image = orig.load()

for i in range(w):
		for j in range(h):
			r = new_image[i, j][0]
			g = new_image[i, j][1]
			b = new_image[i, j][2]
			D = (r + g + b) // 3
      #В оттенки серого
			r = D
			g = D+30
			b = D
      #Для привода к оттенку двигаем одно из значений G+=30 
			if (r > 255):
				r = 255
			if (g > 255):
				g = 255
			if (b > 255):
				b = 255
			draw.point((i, j), (r, g, b))
orig.save("ans.jpg", "JPEG")
orig
