# -*- coding: utf-8 -*-
"""l4_Blanket_Tecnique.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uPiP4H80LREMhoCxqZX4YcLAJHH0YpXX?usp=sharing

Задание: Для полутонового изображения вычислить его размерность Минковского методом построения покрывала.
"""

import numpy as np
import scipy
import cv2
from google.colab.patches import cv2_imshow

originalImage = cv2.imread('bw2.jpg')
grayImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2GRAY)
cv2.imwrite("gs1.jpg", grayImage)

def uS(img):
  k,l=img.shape
  u=np.ndarray(img.shape)
  for i in range(k-1):
    for j in range(l-1):
      u[i][j]=max(img[i][j]+1,max(img[i-1][j],img[i][j-1],img[i+1][j],img[i][j+1]))
  return u

def bS(img):
  k,l=img.shape
  b=np.ndarray(img.shape)
  for i in range(k-1):
    for j in range(l-1):
      b[i][j]=min(img[i][j]-1,min(img[i-1][j],img[i][j-1],img[i+1][j],img[i][j+1]))
  return b

def getVol(u,b):
  k,l=u.shape
  vol=0.0
  for i in range(k):
    for j in range(l):
      vol=vol+u[i][j]-b[i][j]
  return vol

u1=uS(grayImage)
u2=uS(u1)
u3=uS(u2)

b1=bS(grayImage)
b2=bS(b1)
b3=bS(b2)

vol1=getVol(u1,b1)
vol2=getVol(u2,b2)
vol3=getVol(u3,b3)

#формула 22
A_2=(vol2-vol1)/(2)
A_3=(vol3-vol2)/(2)

#формула 21
As1=vol1/2
As2=vol2/4
As3=vol3/6

print("---------",A_2,A_3) 
print(As1, As2, As3)

D1=2-(np.log(As1)-np.log(As2))/(np.log(1)-np.log(2))

D1_2=2-(np.log(As1)-np.log(A_2))/(np.log(1)-np.log(2))

D2=2-(np.log(As2)-np.log(As3))/(np.log(2)-np.log(3))
D2

"""

*   Значение ФР для данного изображения из первой лабораторной: 1.299072
*   Значение фР для данного изображения из текущей лабораторной: 1.290488"""
